export const AUTH_USER = "AUTH_USER";
export const GET_ALL_FARMERS = "GET_ALL_FARMERS";
export const GET_SPECIFIC_FARMER = "GET_SPECIFIC_FARMER";

export const GET_ALL_STAFFS = "GET_ALL_STAFFS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const COFFEE_UPLOAD = "COFFEE_UPLOAD";
export const COFFEE_UPLOAD_FAIL = "COFFEE_UPLOAD_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_PAYABLE_FARMERS = "GET_PAYABLE_FARMERS";
export const CLEAR_PAYABLE_FARMERS = "CLEAR_PAYABLE_FARMERS";

export const PAY_ALL_APPROVED = "PAY_ALL_APPROVED";
export const SINGLE_PAYMENT = "SINGLE_PAYMENT";

export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAIL = "PAYMENT_FAIL";

export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const GET_SINGLE_TRANSACTION = "GET_SINGLE_TRANSACTION";

export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

export const CLEAR_SUCCESS_MSG = "CLEAR_SUCCESS_MSG";

export const GET_ACC_DETAILS = "GET_ACC_DETAILS";

export const SEARCH_USER = "SEARCH_USER";
export const SEARCH_USER_FAIL = "SEARCH_USER_FAIL";
export const CLEAR_USER_SEARCH = "CLEAR_USER_SEARCH";

export const GET_REJECTED_REQUESTS = "GET_REJECTED_REQUESTS";
